name: nextjs-cloud-run

on:
  push:
    branches:
      - develop

env:
  # CLOUD_RUN_PROJECT_ID: ${{ secrets.FIVENET_CLOUD_RUN_PROJECT_NAME }}
  CLOUD_RUN_REGION: asia-northeast1
  # project-name but it can be anything you want
  REPO_NAME: ${{ github.event.repository.name }}
  NEXT_PUBLIC_CHAIN_NAME: ${{ vars.NEXT_PUBLIC_CHAIN_NAME }}
  NEXT_PUBLIC__API_ENDPOINT_SCHEMA_INFO: ${{ vars.NEXT_PUBLIC__API_ENDPOINT_SCHEMA_INFO }}
  API_ENDPOINT_SCHEMA_INFO_2: ${{ vars.API_ENDPOINT_SCHEMA_INFO_2 }}
  NEXT_PUBLIC__API_ENDPOINT_SIX_FIVENET: ${{ vars.NEXT_PUBLIC__API_ENDPOINT_SIX_FIVENET }}
  NEXT_PUBLIC__RPC1_ENDPOINT_SIX_FIVENET: ${{ vars.NEXT_PUBLIC__RPC1_ENDPOINT_SIX_FIVENET }}
  NEXT_PUBLIC__RPC2_ENDPOINT_SIX_FIVENET: ${{ vars.NEXT_PUBLIC__RPC2_ENDPOINT_SIX_FIVENET }}
  NEXT_PUBLIC__SIXSCAN_FIVENET: ${{ vars.NEXT_PUBLIC__SIXSCAN_FIVENET }}
  NEXT_PUBLIC__SIGN_MESSAGE: ${{ vars.NEXT_PUBLIC__SIGN_MESSAGE }}
  NEXT_PUBLIC__SECRET_KEY: ${{ vars.NEXT_PUBLIC__SIGN_MESSAGE }}
  NEXTAUTH_SECRET: ${{ vars.NEXTAUTH_SECRET }}
  NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}
  NEXT_APP_API_ENDPOINT_SCHEMA_INFO: ${{ vars.NEXT_APP_API_ENDPOINT_SCHEMA_INFO }}
  NEXT_APP_API_ENDPOINT_SIX_FIVENET: ${{ vars.NEXT_APP_API_ENDPOINT_SIX_FIVENET }}
  NEXT_APP_RPC1_ENDPOINT_SIX_FIVENET: ${{ vars.NEXT_APP_RPC1_ENDPOINT_SIX_FIVENET }}
  NEXT_APP_RPC2_ENDPOINT_SIX_FIVENET: ${{ vars.NEXT_APP_RPC2_ENDPOINT_SIX_FIVENET }}
  NEXT_APP_FIVENET_SCAN: ${{ vars.NEXT_APP_FIVENET_SCAN }}
  NEXT_APP_SIGN_MESSAGE: ${{ vars.NEXT_APP_SIGN_MESSAGE }}
  NEXT_APP_SECRET_KEY: ${{ vars.NEXT_APP_SECRET_KEY }}
  NEXT_APP_OPENAI_API_KEY: ${{ vars.NEXT_APP_OPENAI_API_KEY }}
  NEXT_TEST: ${{ vars.NEXT_TEST }}

jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    environment: FIVENET
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # This step is where our service account will be authenticated
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.FIVENET_CLOUD_RUN_PROJECT_NAME }}
        service_account_key: ${{ secrets.FIVENET_CLOUD_RUN_SERVICE_ACCOUNT }}
        service_account_email: ${{ secrets.FIVENET_CLOUD_RUN_SERVICE_ACCOUNT_EMAIL }}

    - name: Enable the necessary APIs and enable docker auth
      run: |-
        gcloud services enable containerregistry.googleapis.com
        gcloud services enable run.googleapis.com
        gcloud --quiet auth configure-docker
    - name: Build and tag image
      run: |-
        docker build . --tag "gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA"
    - name: Push image to GCR
      run: |-
        docker push gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA
    - name: Deploy
      run: |-
        gcloud components install beta --quiet
        gcloud beta run deploy $REPO_NAME --image gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA \
          --project $CLOUD_RUN_PROJECT_ID \
          --platform managed \
          --region $CLOUD_RUN_REGION \
          --allow-unauthenticated \
          --set-env-vars NEXT_PUBLIC_CHAIN_NAME=$NEXT_PUBLIC_CHAIN_NAME,NEXT_PUBLIC_API_ENDPOINT_SCHEMA_INFO=$NEXT_PUBLIC_API_ENDPOINT_SCHEMA_INFO \
          --set-env-vars API_ENDPOINT_SCHEMA_INFO_2=$API_ENDPOINT_SCHEMA_INFO_2,NEXT_PUBLIC_API_ENDPOINT_SIX_FIVENET=$NEXT_PUBLIC_API_ENDPOINT_SIX_FIVENET \
          --set-env-vars NEXT_PUBLIC_RPC1_ENDPOINT_SIX_FIVENET=$NEXT_PUBLIC_RPC1_ENDPOINT_SIX_FIVENET,NEXT_PUBLIC_RPC2_ENDPOINT_SIX_FIVENET=$NEXT_PUBLIC_RPC2_ENDPOINT_SIX_FIVENET \
          --set-env-vars NEXT_PUBLIC_SIXSCAN_FIVENET=$NEXT_PUBLIC_SIXSCAN_FIVENET,NEXT_PUBLIC_SIGN_MESSAGE=$NEXT_PUBLIC_SIGN_MESSAGE,NEXT_PUBLIC_SECRET_KEY=$NEXT_PUBLIC_SECRET_KEY \
          --set-env-vars NEXTAUTH_SECRET=$NEXTAUTH_SECRET,NEXTAUTH_URL=$NEXTAUTH_URL,NEXT_APP_API_ENDPOINT_SCHEMA_INFO=$NEXT_APP_API_ENDPOINT_SCHEMA_INFO \
          --set-env-vars NEXT_APP_API_ENDPOINT_SIX_FIVENET=$NEXT_APP_API_ENDPOINT_SIX_FIVENET,NEXT_APP_RPC1_ENDPOINT_SIX_FIVENET=$NEXT_APP_RPC1_ENDPOINT_SIX_FIVENET \
          --set-env-vars NEXT_APP_RPC2_ENDPOINT_SIX_FIVENET=$NEXT_APP_RPC2_ENDPOINT_SIX_FIVENET,NEXT_APP_FIVENET_SCAN=$NEXT_APP_FIVENET_SCAN,NEXT_APP_SIGN_MESSAGE=$NEXT_APP_SIGN_MESSAGE \
          --set-env-vars NEXT_APP_SECRET_KEY=$NEXT_APP_SECRET_KEY,NEXT_APP_OPENAI_API_KEY=$NEXT_APP_OPENAI_API_KEY,NEXT_TEST=$NEXT_TEST \
          --quiet